apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: peakblockai 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: peakblockai 
    spec:
      containers:
        - name: peakblockai 
          image: cohub.azurecr.io/peakblockai
          ports:
          - containerPort: 5555